# Generated by Django 3.2.18 on 2024-02-13 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('translate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField()),
                ('right_word', models.CharField(max_length=100)),
                ('wrong_words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
        ),
    ]
