# Generated by Django 3.2.18 on 2024-02-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='users', verbose_name='фото'),
        ),
    ]
