# Generated by Django 3.2.18 on 2024-02-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='right_answers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='wrong_answers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
